name: build-ubuntu_x1_defconfig

on:
  workflow_dispatch:
  push:
    branches-ignore: [ 'master' ]
  pull_request:
    branches-ignore: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm
    steps:

    - name: deps
      run: |
        apt install -y \
          build-essential \
          debhelper-compat \
          libdw-dev \
          libelf-dev
          
    - name: checkout
      uses: actions/checkout@v4

    - name: mrproper
      run: |
        make ARCH=arm64 mrproper
        
    - name: configure
      run: |
        make ARCH=arm64 -j ubuntu_x1e_defconfig

        scripts/config --enable CONFIG_BLK_DEV_INITRD=y
        scripts/config --enable CONFIG_RD_GZIP
        scripts/config --enable CONFIG_RD_ZSTD

        scripts/config --disable SYSTEM_TRUSTED_KEYS
        scripts/config --disable SYSTEM_REVOCATION_KEYS
        
    - name: build
      run: |
        VERS=$(make kernelversion)
        HASH=$(git rev-parse HEAD)
        export LOCALVERSION="-jg-g${HASH:0:12}"
        echo "Building kernel version: '${VERS}${LOCALVERSION}'"
        
        make ARCH=arm64 -j$(nproc)

    - name: package
      run: |
        make ARCH=arm64 -j$(nproc) bindeb-pkg

        
